In [76]:
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt

In [84]:
f = open("C:/Navneet/College/Fall21/NLP/Song-Genre-Identifier/DataProcessor/dataset/processed/songList.json")
data = json.load(f)
f.close()
df = pd.json_normalize(data['songs'])
df.head()

,Artist,Title,Lyrics,Genres
0,Adam Ant,Something Girls,"[[adam, pirroni], [every, girl, something, gir...",Rock
1,Gob,Face the Ashes,"[[erase, get, world, sale], [walk, away, well,...",Rock
2,Lionel Richie,Tonight Will Be Alright,"[[little, darling], [long], [think, ya], [feel...",R&B
3,Blue Rodeo,Floating,"[[lead, vocal, greg], [well, late, night, conv...",Rock
4,Tesla,Caught In A Dream,"[[imagine], [whole, world, sharin, one, big, k...",Rock

In [88]:
df['Lyrics'][0][0][1]

'pirroni'

In [89]:
def totalWords(arr):
    tot = 0
    freq = {}
    print(arr)
    for x in arr:
        tot = tot + len(x)
        for y in x:
            if(y in freq):
                freq[y]=freq[y]+1
            else:
                freq[y]=1
    WordMax = max(zip(freq.values(), freq.keys()))[1]
    WordFreq = max(zip(freq.values(), freq.keys()))[0]
    return tot, len(freq), WordMax, WordFreq

In [ ]:
lengthArray = []
uniqueArray = []
mostFrequentWord = []
freqOfMFW = []
for index,row in df.iterrows():
    n,freq,mfw,fmfw = totalWords(row.Lyrics)
    lengthArray.append(n)
    uniqueArray.append(freq)
    mostFrequentWord.append(mfw)
    freqOfMFW.append(fmfw)
df['TotalWords'] = pd.Series(lengthArray, index=df.index)
df['UniqueWords'] = pd.Series(uniqueArray, index = df.index)
df['MostFrequentWords'] = pd.Series(mostFrequentWord, index=df.index)
df['FrequencyOfMFW'] = pd.Series(freqOfMFW, index=df.index)

In [91]:
df['MostFrequentWords']

0          girl
1          away
2       alright
3          well
4         dream
         ...
1065       slam
1066        lie
1067       burn
1068       girl
1069    camelot
Name: MostFrequentWords, Length: 1070, dtype: object

In [92]:
df.head()

,Artist,Title,Lyrics,Genres,TotalWords,UniqueWords,MostFrequentWords,FrequencyOfMFW
0,Adam Ant,Something Girls,"[[adam, pirroni], [every, girl, something, gir...",Rock,76,35,girl,17
1,Gob,Face the Ashes,"[[erase, get, world, sale], [walk, away, well,...",Rock,58,50,away,3
2,Lionel Richie,Tonight Will Be Alright,"[[little, darling], [long], [think, ya], [feel...",R&B,100,53,alright,13
3,Blue Rodeo,Floating,"[[lead, vocal, greg], [well, late, night, conv...",Rock,104,81,well,4
4,Tesla,Caught In A Dream,"[[imagine], [whole, world, sharin, one, big, k...",Rock,166,79,dream,10

In [95]:
def sentenceProcessing(arr):
    freq = {}
    total = 0
    for x in arr:
        sent = ' '.join(x)
        if sent in freq:
            freq[sent] = freq[sent]+1
        else:
            freq[sent] = 1
        total = total+1
    sentMax = max(zip(freq.values(), freq.keys()))[1]
    sentCount = max(zip(freq.values(), freq.keys()))[0]
    return total, sentMax, sentCount

In [96]:
sentM = []
sentC = []
totalS = []
for index,row in df.iterrows():
    total, sentMax, sentCount = sentenceProcessing(row['Lyrics'])
    sentM.append(sentMax)
    sentC.append(sentCount)
    totalS.append(total)
df['TotalSentences'] = pd.Series(totalS, index = df.index)
df['MostFrequentSentence'] = pd.Series(sentM, index = df.index)
df['CountMostSentence'] = pd.Series(sentC, index = df.index)

In [97]:
df.head()

,Artist,Title,Lyrics,Genres,TotalWords,UniqueWords,MostFrequentWords,FrequencyOfMFW,TotalSentences,MostFrequentSentence,CountMostSentence
0,Adam Ant,Something Girls,"[[adam, pirroni], [every, girl, something, gir...",Rock,76,35,girl,17,23,every girl something girl,7
1,Gob,Face the Ashes,"[[erase, get, world, sale], [walk, away, well,...",Rock,58,50,away,3,14,someone kill,2
2,Lionel Richie,Tonight Will Be Alright,"[[little, darling], [long], [think, ya], [feel...",R&B,100,53,alright,13,35,cause tonight alright,3
3,Blue Rodeo,Floating,"[[lead, vocal, greg], [well, late, night, conv...",Rock,104,81,well,4,38,throw line,2
4,Tesla,Caught In A Dream,"[[imagine], [whole, world, sharin, one, big, k...",Rock,166,79,dream,10,57,way dream,6

In [100]:
df.to_json(r'C:\Navneet\College\Fall21\NLP\Song-Genre-Identifier\DataAnalysis\LyricsAnalysis\dataset.json')
df.to_csv(r'C:\Navneet\College\Fall21\NLP\Song-Genre-Identifier\DataAnalysis\LyricsAnalysis\dataset.csv')